### ISSUE TITLE
bug  If the content is loaded dynamically

### ISSUE THREAD

**Issue by chavesgu** [creotip/vue-prism.js#2]
If the content is loaded dynamically，the content Can not  be compile

**Comment by nathanboktae** [comment]
In a 15-line component it's not a bug, it's a design flaw. It's only rendered once on `mount` and never connects to vue's reactivity system at all. Use [vue-prism-component](https://www.npmjs.com/package/vue-prism-component) for a proper implementation.

**Comment by warrebuysse** [comment]
@nathanboktae Then I would explicitly state this in your readme.md file. I was having the same issue, and had to find out by diving into the 15-line source code. Since it's called vue-prism I expected full Vue functionality here.

**Comment by nathanboktae** [comment]
I think you meant to tag @creotip  and not me @warrebuysse . This is not my project.

**Comment by TechPlasma** [comment]
I just ended up forking it and changing "mounted" to "updated" this basically solved the issue for me and my use-case of having a markdown converter that updates vue constantly
